from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('contacts/<int:pk>/', ContactDetailView.as_view(), name='contact_detail'),
    path('contacts/add/', ContactCreateView.as_view(), name='contact_create'),
    path('contacts/<int:pk>/edit/', ContactUpdateView.as_view(), name='contact_update'),
    path('contacts/<int:pk>/delete/', ContactDeleteView.as_view(), name='contact_delete'),
    path('find-us/', FindUsView.as_view(), name='find_us'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('categories/add/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/edit/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
    path('dishes/', DishListView.as_view(), name='dish_list'),
    path('dishes/category/<int:category_id>/', DishListView.as_view(), name='dish_list_by_category'),
    path('dishes/<int:pk>/', DishDetailView.as_view(), name='dish_detail'),
    path('dishes/add/', DishCreateView.as_view(), name='dish_create'),
    path('dishes/<int:pk>/edit/', DishUpdateView.as_view(), name='dish_update'),
    path('dishes/<int:pk>/delete/', DishDeleteView.as_view(), name='dish_delete'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/<int:dish_id>/', CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:dish_id>/', CartRemoveView.as_view(), name='cart_remove'),
    path('promotions/', PromotionListView.as_view(), name='promotion_list'),
    path('promotions/<int:pk>/', PromotionDetailView.as_view(), name='promotion_detail'),
    path('promotions/add/', PromotionCreateView.as_view(), name='promotion_create'),
    path('promotions/<int:pk>/edit/', PromotionUpdateView.as_view(), name='promotion_update'),
    path('promotions/<int:pk>/delete/', PromotionDeleteView.as_view(), name='promotion_delete'),
    path('orders/', OrderListView.as_view(), name='order_list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('orders/add/', OrderCreateView.as_view(), name='order_create'),
    path('orders/<int:pk>/edit/', OrderUpdateView.as_view(), name='order_update'),
    path('orders/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),
    path('delivery/', DeliveryView.as_view(), name='delivery'),
]